"""
Django settings for jobsafety project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q^@d+x*12sntw381@2df_&j1gyk@15$wc6k3(prid$yd+xkh40'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jobsafe',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jobsafety.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobsafety.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'tr_TR'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_ROOT = BASE_DIR + '/static/'
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/media/'

#STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

ADMINS = (
    ('Necip', 'sunmaznecip@gmail.com'),
)

BLOG_FEED_TITLE = "İş Güvenliği Analisti"
BLOG_FEED_DESCRIPTION = "İş güvenliği analizlerinin ölçümlerini yapar."

CONTACT_EMAIL = "sunmaznecip@gmail.com"
APPEND_SLAH = False

# Django Suit configuration example
SUIT_CONFIG = {
    # header
    'ADMIN_NAME': 'İş Güvenliği Analisti',
    # 'HEADER_DATE_FORMAT': 'l, j. F Y',
    # 'HEADER_TIME_FORMAT': 'H:i',

    # forms
    # 'SHOW_REQUIRED_ASTERISK': True,  # Default True
    # 'CONFIRM_UNSAVED_CHANGES': True, # Default True

    # menu
    # 'SEARCH_URL': '/admin/auth/user/',
    # 'MENU_ICONS': {
    #    'sites': 'icon-leaf',
    #    'auth': 'icon-lock',
    # },
    # 'MENU_OPEN_FIRST_CHILD': True, # Default True
    # 'MENU_EXCLUDE': ('auth.group',),
    # 'MENU': (
    #     'sites',
    #     {'app': 'auth', 'icon':'icon-lock', 'models': ('user', 'group')},
    #     {'label': 'Settings', 'icon':'icon-cog', 'models': ('auth.user', 'auth.group')},
    #     {'label': 'Support', 'icon':'icon-question-sign', 'url': '/support/'},
    # ),

    # misc
    # 'LIST_PER_PAGE': 15
}

CITIES = [('Adana', 'Adana'), ('Adıyaman', 'Adıyaman'), ('Afyon' , 'Afyon'), ('Ağrı', 'Ağrı'), ('Amasya', 'Amasya'),
          ('Ankara', 'Ankara'), ('Antalya', 'Antalya'), ('Artvin', 'Artvin'), ('Aydın', 'Aydın'), ('Balıkesir', 'Balıkesir'),
          ('Bilecik', 'Bilecik'), ('Bingöl', 'Bingöl'), ('Bitlis', 'Bitlis'), ('Bolu', 'Bolu'), ('Burdur', 'Burdur'),
          ('Bursa', 'Bursa'), ('Çanakkale', 'Çanakkale'), ('Çankırı', 'Çankırı'), ('Çorum', 'Çorum'), ('Denizli', 'Denizli'),
          ('Diyarbakır', 'Diyarbakır'), ('Edirne', 'Edirne'), ('Elazığ', 'Elazığ'), ('Erzincan', 'Erzincan'), ('Erzurum', 'Erzurum'),
          ('Eskişehir', 'Eskişehir'), ('Gaziantep', 'Gaziantep'), ('Giresun', 'Giresun'), ('Gümüşhane', 'Gümüşhane'),
          ('Hakkari', 'Hakkari'), ('Hatay', 'Hatay'), ('Isparta', 'Isparta'), ('Mersin', 'Mersin'), ('İstanbul', 'İstanbul'),
          ('İzmir', 'İzmir'), ('Kars', 'Kars'), ('Kastamonu', 'Kastamonu'), ('Kayseri', 'Kayseri'), ('Kırklareli', 'Kırklareli'),
          ('Kırşehir', 'Kırşehir'), ('Kocaeli', 'Kocaeli'), ('Konya', 'Konya'), ('Kütahya', 'Kütahya'), ('Malatya', 'Malatya'),
          ('Manisa', 'Manisa'), ('Kahramanmaraş', 'Kahramanmaraş'), ('Mardin', 'Mardin'), ('Muğla', 'Muğla'), ('Muş', 'Muş'),
          ('Nevşehir', 'Nevşehir'), ('Niğde', 'Niğde'), ('Ordu', 'Ordu'), ('Rize', 'Rize'), ('Sakarya', 'Sakarya'),
          ('Samsun', 'Samsun'), ('Siirt', 'Siirt'), ('Sinop', 'Sinop'), ('Sivas', 'Sivas'), ('Tekirdağ', 'Tekirdağ'),
          ('Tokat', 'Tokat'), ('Trabzon', 'Trabzon'), ('Tunceli', 'Tunceli'), ('Şanlıurfa', 'Şanlıurfa'), ('Uşak', 'Uşak'),
          ('Van', 'Van'), ('Yozgat', 'Yozgat'), ('Zonguldak', 'Zonguldak'), ('Aksaray', 'Aksaray'), ('Bayburt', 'Bayburt'),
          ('Karaman', 'Karaman'), ('Kırıkkale', 'Kırıkkale'), ('Batman', 'Batman'), ('Şırnak', 'Şırnak'),
          ('Bartın', 'Bartın'), ('Ardahan', 'Ardahan'), ('Iğdır', 'Iğdır'), ('Yalova', 'Yalova'), ('Karabük', 'Karabük'),
          ('Kilis', 'Kilis'), ('Osmaniye', 'Osmaniye'), ('Düzce', 'Düzce')]